import type { MetadataRoute } from "next";
import { COUNTRY_META } from "@/lib/oecd";

const BASE = "https://easybuildcalc.com";

function codeToSlug(code: string): string {
  return COUNTRY_META[code].name.toLowerCase().replace(/\s+/g, "-").replace(/[^a-z0-9-]/g, "");
}

const calculators = [
  { slug: "concrete-calculator",     priority: 0.9, changeFreq: "monthly" as const },
  { slug: "board-foot-calculator",   priority: 0.9, changeFreq: "monthly" as const },
  { slug: "asphalt-calculator",      priority: 0.9, changeFreq: "monthly" as const },
  { slug: "paint-calculator",        priority: 0.9, changeFreq: "monthly" as const },
  { slug: "drywall-calculator",      priority: 0.8, changeFreq: "monthly" as const },
  { slug: "roof-pitch-calculator",   priority: 0.8, changeFreq: "monthly" as const },
  { slug: "shingles-calculator",     priority: 0.8, changeFreq: "monthly" as const },
  { slug: "sand-calculator",         priority: 0.8, changeFreq: "monthly" as const },
  { slug: "mulch-calculator",        priority: 0.8, changeFreq: "monthly" as const },
  { slug: "gravel-calculator",       priority: 0.8, changeFreq: "monthly" as const },
  { slug: "rebar-calculator",        priority: 0.7, changeFreq: "monthly" as const },
  { slug: "brick-calculator",        priority: 0.7, changeFreq: "monthly" as const },
  { slug: "stud-calculator",         priority: 0.7, changeFreq: "monthly" as const },
  { slug: "flooring-calculator",     priority: 0.7, changeFreq: "monthly" as const },
  { slug: "deck-calculator",         priority: 0.7, changeFreq: "monthly" as const },
  { slug: "fence-calculator",        priority: 0.7, changeFreq: "monthly" as const },
  { slug: "insulation-calculator",   priority: 0.7, changeFreq: "monthly" as const },
  { slug: "lumber-calculator",       priority: 0.7, changeFreq: "monthly" as const },
  { slug: "concrete-mix-calculator", priority: 0.6, changeFreq: "monthly" as const },
  { slug: "tile-calculator",         priority: 0.9, changeFreq: "monthly" as const },
  { slug: "paver-calculator",        priority: 0.9, changeFreq: "monthly" as const },
  { slug: "stair-calculator",        priority: 0.9, changeFreq: "monthly" as const },
  { slug: "sod-calculator",          priority: 0.8, changeFreq: "monthly" as const },
  { slug: "cubic-yard-calculator",   priority: 0.9, changeFreq: "monthly" as const },
  { slug: "topsoil-calculator",      priority: 0.9, changeFreq: "monthly" as const },
  { slug: "retaining-wall-calculator", priority: 0.8, changeFreq: "monthly" as const },
  { slug: "carpet-calculator",       priority: 0.8, changeFreq: "monthly" as const },
  { slug: "block-calculator",        priority: 0.8, changeFreq: "monthly" as const },
  { slug: "excavation-calculator",    priority: 0.8, changeFreq: "monthly" as const },
  { slug: "metal-roofing-calculator", priority: 0.9, changeFreq: "monthly" as const },
  { slug: "wallpaper-calculator",     priority: 0.8, changeFreq: "monthly" as const },
  { slug: "concrete-curb-calculator", priority: 0.8, changeFreq: "monthly" as const },
  { slug: "window-calculator",               priority: 0.9, changeFreq: "monthly" as const },
  { slug: "fence-post-concrete-calculator",  priority: 0.8, changeFreq: "monthly" as const },
  { slug: "window-rough-opening-calculator", priority: 0.8, changeFreq: "monthly" as const },
  { slug: "basement-waterproofing-calculator", priority: 0.8, changeFreq: "monthly" as const },
  { slug: "hvac-duct-calculator",            priority: 0.8, changeFreq: "monthly" as const },
  { slug: "septic-tank-calculator",          priority: 0.8, changeFreq: "monthly" as const },

  // Cost calculators (Phase 2 — head-money queries)
  { slug: "concrete-patio-cost-calculator",  priority: 0.9, changeFreq: "monthly" as const },
  { slug: "deck-cost-calculator",            priority: 0.9, changeFreq: "monthly" as const },
];

// Project bundles (Phase 3 — head-build queries)
const projectBundles = [
  { slug: "build-a-deck",     priority: 0.9, changeFreq: "monthly" as const },
  { slug: "install-a-fence",  priority: 0.9, changeFreq: "monthly" as const },
];

const countryPages = Object.keys(COUNTRY_META).map((code) => ({
  url: `${BASE}/construction-market/${codeToSlug(code)}`,
  lastModified: new Date(),
  changeFrequency: "monthly" as const,
  priority: 0.6,
}));

export default function sitemap(): MetadataRoute.Sitemap {
  const now = new Date();

  return [
    { url: BASE,                             lastModified: now, changeFrequency: "weekly",  priority: 1.0 },
    { url: `${BASE}/material-prices`,        lastModified: now, changeFrequency: "monthly", priority: 0.8 },
    { url: `${BASE}/housing-starts`,         lastModified: now, changeFrequency: "monthly", priority: 0.8 },
    { url: `${BASE}/lumber-market`,          lastModified: now, changeFrequency: "monthly", priority: 0.7 },
    ...countryPages,
    { url: `${BASE}/about`,                  lastModified: now, changeFrequency: "yearly",  priority: 0.5 },
    { url: `${BASE}/contact`,                lastModified: now, changeFrequency: "yearly",  priority: 0.4 },
    { url: `${BASE}/guides`,                 lastModified: now, changeFrequency: "monthly", priority: 0.8 },
    { url: `${BASE}/guides/osb-vs-plywood`,                         lastModified: now, changeFrequency: "yearly", priority: 0.8 },
    { url: `${BASE}/guides/metal-roofing-vs-asphalt-shingles`,      lastModified: now, changeFrequency: "yearly", priority: 0.8 },
    { url: `${BASE}/guides/concrete-block-vs-poured-foundation`,    lastModified: now, changeFrequency: "yearly", priority: 0.8 },
    { url: `${BASE}/guides/gravel-vs-asphalt-driveway`,             lastModified: now, changeFrequency: "yearly", priority: 0.8 },
    { url: `${BASE}/guides/vinyl-vs-hardwood-flooring`,             lastModified: now, changeFrequency: "yearly", priority: 0.8 },
    { url: `${BASE}/guides/spray-foam-vs-fiberglass-insulation`,    lastModified: now, changeFrequency: "yearly", priority: 0.8 },
    { url: `${BASE}/howto`,                                        lastModified: now, changeFrequency: "monthly", priority: 0.8 },
    { url: `${BASE}/howto/concrete-patio-cost`,                    lastModified: now, changeFrequency: "yearly", priority: 0.8 },
    { url: `${BASE}/howto/how-to-frame-a-wall`,                    lastModified: now, changeFrequency: "yearly", priority: 0.8 },
    { url: `${BASE}/faq`,                                           lastModified: now, changeFrequency: "monthly", priority: 0.8 },
    { url: `${BASE}/faq/how-many-gallons-of-paint-for-12x12-room`,              lastModified: now, changeFrequency: "yearly", priority: 0.9 },
    { url: `${BASE}/faq/how-much-rebar-for-10x10-slab`,                         lastModified: now, changeFrequency: "yearly", priority: 0.9 },
    { url: `${BASE}/faq/how-many-bags-of-concrete-for-10x10-slab`,              lastModified: now, changeFrequency: "yearly", priority: 0.9 },
    { url: `${BASE}/faq/how-many-sheets-of-drywall-for-12x12-room`,             lastModified: now, changeFrequency: "yearly", priority: 0.9 },
    { url: `${BASE}/faq/how-many-studs-for-16-foot-wall`,                       lastModified: now, changeFrequency: "yearly", priority: 0.9 },
    { url: `${BASE}/faq/how-much-mulch-for-100-square-feet`,                    lastModified: now, changeFrequency: "yearly", priority: 0.9 },
    { url: `${BASE}/faq/how-many-pavers-for-10x10-patio`,                       lastModified: now, changeFrequency: "yearly", priority: 0.9 },
    { url: `${BASE}/faq/how-many-shingles-for-1500-sq-ft-roof`,                 lastModified: now, changeFrequency: "yearly", priority: 0.9 },
    { url: `${BASE}/faq/how-many-concrete-blocks-for-40-foot-wall`,             lastModified: now, changeFrequency: "yearly", priority: 0.9 },
    { url: `${BASE}/faq/how-many-rolls-of-sod-for-1000-sq-ft`,                  lastModified: now, changeFrequency: "yearly", priority: 0.9 },
    { url: `${BASE}/faq/how-much-gravel-for-200-foot-driveway`,                 lastModified: now, changeFrequency: "yearly", priority: 0.9 },
    { url: `${BASE}/faq/how-many-tiles-for-12x12-room`,                         lastModified: now, changeFrequency: "yearly", priority: 0.9 },
    { url: `${BASE}/faq/how-many-shingles-in-a-bundle`,                         lastModified: now, changeFrequency: "yearly", priority: 0.9 },
    { url: `${BASE}/faq/how-many-80lb-bags-of-concrete-in-a-yard`,              lastModified: now, changeFrequency: "yearly", priority: 0.9 },
    { url: `${BASE}/faq/how-many-gallons-of-paint-for-a-bedroom`,               lastModified: now, changeFrequency: "yearly", priority: 0.9 },
    { url: `${BASE}/faq/how-many-bricks-per-square-foot`,                       lastModified: now, changeFrequency: "yearly", priority: 0.9 },
    { url: `${BASE}/faq/how-many-nails-per-shingle`,                            lastModified: now, changeFrequency: "yearly", priority: 0.9 },
    { url: `${BASE}/faq/how-much-does-a-square-of-shingles-cover`,             lastModified: now, changeFrequency: "yearly", priority: 0.9 },
    { url: `${BASE}/faq/how-many-bags-of-concrete-for-a-fence-post`,           lastModified: now, changeFrequency: "yearly", priority: 0.9 },
    { url: `${BASE}/faq/how-many-square-feet-in-a-box-of-laminate-flooring`,   lastModified: now, changeFrequency: "yearly", priority: 0.9 },
    { url: `${BASE}/faq/how-many-deck-screws-per-board`,                        lastModified: now, changeFrequency: "yearly", priority: 0.9 },
    { url: `${BASE}/faq/how-much-paint-for-a-front-door`,                       lastModified: now, changeFrequency: "yearly", priority: 0.9 },
    { url: `${BASE}/faq/how-many-bags-of-quikrete-per-fence-post`,             lastModified: now, changeFrequency: "yearly", priority: 0.9 },
    { url: `${BASE}/faq/how-many-gallons-of-paint-for-a-10x10-room`,           lastModified: now, changeFrequency: "yearly", priority: 0.9 },
    { url: `${BASE}/faq/how-much-mulch-for-200-square-feet`,                    lastModified: now, changeFrequency: "yearly", priority: 0.9 },
    { url: `${BASE}/faq/how-much-soil-for-a-4x8-raised-bed`,                   lastModified: now, changeFrequency: "yearly", priority: 0.9 },
    { url: `${BASE}/faq/how-many-bags-of-concrete-for-a-12x12-slab`,           lastModified: now, changeFrequency: "yearly", priority: 0.9 },
    { url: `${BASE}/faq/how-much-concrete-for-a-20x20-slab`,                   lastModified: now, changeFrequency: "yearly", priority: 0.9 },
    { url: `${BASE}/faq/how-many-bundles-of-shingles-for-a-10x10-shed`,        lastModified: now, changeFrequency: "yearly", priority: 0.9 },
    { url: `${BASE}/faq/how-many-bundles-of-shingles-for-a-12x16-shed`,        lastModified: now, changeFrequency: "yearly", priority: 0.9 },
    { url: `${BASE}/faq/how-many-deck-boards-for-a-12x12-deck`,                lastModified: now, changeFrequency: "yearly", priority: 0.9 },
    { url: `${BASE}/faq/how-many-deck-boards-for-a-16x20-deck`,                lastModified: now, changeFrequency: "yearly", priority: 0.9 },
    { url: `${BASE}/faq/how-many-fence-pickets-for-100-feet`,                  lastModified: now, changeFrequency: "yearly", priority: 0.9 },
    { url: `${BASE}/faq/how-many-shingles-for-a-24x24-garage`,                 lastModified: now, changeFrequency: "yearly", priority: 0.9 },
    { url: `${BASE}/faq/how-many-studs-for-a-12x12-room`,                      lastModified: now, changeFrequency: "yearly", priority: 0.9 },
    { url: `${BASE}/faq/how-many-studs-for-a-20-foot-wall`,                    lastModified: now, changeFrequency: "yearly", priority: 0.9 },
    { url: `${BASE}/faq/how-many-studs-for-a-24-foot-wall`,                    lastModified: now, changeFrequency: "yearly", priority: 0.9 },
    { url: `${BASE}/faq/how-much-caulk-for-a-bathtub`,                         lastModified: now, changeFrequency: "yearly", priority: 0.9 },
    { url: `${BASE}/faq/how-much-drywall-for-a-2000-sq-ft-house`,              lastModified: now, changeFrequency: "yearly", priority: 0.9 },
    { url: `${BASE}/faq/how-much-paint-for-a-12x15-room`,                      lastModified: now, changeFrequency: "yearly", priority: 0.9 },
    { url: `${BASE}/faq/how-much-rebar-for-a-driveway`,                        lastModified: now, changeFrequency: "yearly", priority: 0.9 },
    { url: `${BASE}/faq/how-much-sand-for-a-10x10-patio`,                      lastModified: now, changeFrequency: "yearly", priority: 0.9 },
    { url: `${BASE}/faq/how-many-bundles-of-shingles-for-1000-sq-ft`,          lastModified: now, changeFrequency: "yearly", priority: 0.9 },
    { url: `${BASE}/faq/how-much-pea-gravel-for-a-10x10-area`,                 lastModified: now, changeFrequency: "yearly", priority: 0.9 },
    { url: `${BASE}/faq/how-many-bricks-for-a-10x10-patio`,                    lastModified: now, changeFrequency: "yearly", priority: 0.9 },
    { url: `${BASE}/faq/how-many-bags-of-mulch-for-10-yards`,                  lastModified: now, changeFrequency: "yearly", priority: 0.9 },
    { url: `${BASE}/faq/how-many-bags-of-quikrete-for-a-10x10-slab`,           lastModified: now, changeFrequency: "yearly", priority: 0.9 },
    { url: `${BASE}/faq/how-much-does-a-yard-of-concrete-weigh`,               lastModified: now, changeFrequency: "yearly", priority: 0.9 },
    { url: `${BASE}/faq/how-thick-should-a-concrete-driveway-be`,              lastModified: now, changeFrequency: "yearly", priority: 0.9 },
    { url: `${BASE}/faq/how-many-square-feet-does-a-bundle-of-shingles-cover`, lastModified: now, changeFrequency: "yearly", priority: 0.9 },
    { url: `${BASE}/faq/how-many-bags-of-concrete-in-a-cubic-yard`,            lastModified: now, changeFrequency: "yearly", priority: 0.9 },
    { url: `${BASE}/faq/how-many-board-feet-in-a-2x4x8`,                       lastModified: now, changeFrequency: "yearly", priority: 0.9 },
    { url: `${BASE}/faq/how-thick-should-asphalt-be-for-a-driveway`,           lastModified: now, changeFrequency: "yearly", priority: 0.9 },
    { url: `${BASE}/faq/how-much-gravel-under-concrete-slab`,                  lastModified: now, changeFrequency: "yearly", priority: 0.9 },
    { url: `${BASE}/faq/how-much-paint-for-kitchen-cabinets`,                  lastModified: now, changeFrequency: "yearly", priority: 0.9 },
    { url: `${BASE}/faq/how-many-tons-of-gravel-for-a-driveway`,               lastModified: now, changeFrequency: "yearly", priority: 0.9 },
    { url: `${BASE}/faq/how-many-pallets-of-sod-for-1-acre`,                   lastModified: now, changeFrequency: "yearly", priority: 0.9 },
    { url: `${BASE}/faq/how-many-studs-for-a-8-foot-wall`,                     lastModified: now, changeFrequency: "yearly", priority: 0.9 },
    { url: `${BASE}/faq/how-much-mulch-for-300-square-feet`,                   lastModified: now, changeFrequency: "yearly", priority: 0.9 },
    { url: `${BASE}/faq/how-many-bags-of-mulch-for-100-square-feet`,           lastModified: now, changeFrequency: "yearly", priority: 0.9 },
    { url: `${BASE}/faq/how-many-pounds-of-grass-seed-for-1000-sq-ft`,         lastModified: now, changeFrequency: "yearly", priority: 0.9 },
    { url: `${BASE}/faq/how-many-wheelbarrow-loads-in-a-cubic-yard`,           lastModified: now, changeFrequency: "yearly", priority: 0.9 },
    { url: `${BASE}/faq/how-much-concrete-for-a-6x6-post`,                     lastModified: now, changeFrequency: "yearly", priority: 0.9 },
    { url: `${BASE}/faq/how-much-sand-for-a-4x4-sandbox`,                      lastModified: now, changeFrequency: "yearly", priority: 0.9 },
    { url: `${BASE}/faq/how-many-bags-of-concrete-for-a-20x20-slab`,           lastModified: now, changeFrequency: "yearly", priority: 0.9 },
    { url: `${BASE}/faq/how-many-bags-of-concrete-for-a-mailbox-post`,         lastModified: now, changeFrequency: "yearly", priority: 0.9 },
    { url: `${BASE}/faq/how-many-bags-of-sand-for-pavers`,                     lastModified: now, changeFrequency: "yearly", priority: 0.9 },
    { url: `${BASE}/faq/how-many-bricks-for-a-20x20-patio`,                    lastModified: now, changeFrequency: "yearly", priority: 0.9 },
    { url: `${BASE}/faq/how-many-cinder-blocks-for-a-10x10-shed`,              lastModified: now, changeFrequency: "yearly", priority: 0.9 },
    { url: `${BASE}/faq/how-many-cubic-yards-in-a-dump-truck-load`,            lastModified: now, changeFrequency: "yearly", priority: 0.9 },
    { url: `${BASE}/faq/how-many-deck-boards-for-a-10x10-deck`,                lastModified: now, changeFrequency: "yearly", priority: 0.9 },
    { url: `${BASE}/faq/how-many-deck-boards-for-a-20x20-deck`,                lastModified: now, changeFrequency: "yearly", priority: 0.9 },
    { url: `${BASE}/faq/how-many-gallons-of-paint-for-a-20x20-room`,           lastModified: now, changeFrequency: "yearly", priority: 0.9 },
    { url: `${BASE}/faq/how-many-nails-for-a-square-of-shingles`,              lastModified: now, changeFrequency: "yearly", priority: 0.9 },
    { url: `${BASE}/faq/how-many-pavers-for-a-12x12-patio`,                    lastModified: now, changeFrequency: "yearly", priority: 0.9 },
    { url: `${BASE}/faq/how-many-rolls-of-sod-for-500-sq-ft`,                  lastModified: now, changeFrequency: "yearly", priority: 0.9 },
    { url: `${BASE}/faq/how-many-shingles-for-a-12x12-shed`,                   lastModified: now, changeFrequency: "yearly", priority: 0.9 },
    { url: `${BASE}/faq/how-many-square-feet-does-a-roll-of-sod-cover`,        lastModified: now, changeFrequency: "yearly", priority: 0.9 },
    { url: `${BASE}/faq/how-many-square-feet-does-a-ton-of-asphalt-cover`,     lastModified: now, changeFrequency: "yearly", priority: 0.9 },
    { url: `${BASE}/faq/how-many-square-feet-in-a-roll-of-carpet`,             lastModified: now, changeFrequency: "yearly", priority: 0.9 },
    { url: `${BASE}/faq/how-many-yards-of-concrete-for-a-30x30-slab`,          lastModified: now, changeFrequency: "yearly", priority: 0.9 },
    { url: `${BASE}/faq/how-much-concrete-for-deck-footings`,                  lastModified: now, changeFrequency: "yearly", priority: 0.9 },
    { url: `${BASE}/faq/how-much-gravel-for-a-100-foot-driveway`,              lastModified: now, changeFrequency: "yearly", priority: 0.9 },
    { url: `${BASE}/faq/how-much-grout-for-tile-floor`,                        lastModified: now, changeFrequency: "yearly", priority: 0.9 },
    { url: `${BASE}/faq/how-much-mulch-for-500-square-feet`,                   lastModified: now, changeFrequency: "yearly", priority: 0.9 },
    { url: `${BASE}/faq/how-many-tons-in-a-cubic-yard-of-dirt`,                lastModified: now, changeFrequency: "yearly", priority: 0.9 },
    { url: `${BASE}/privacy`,                lastModified: now, changeFrequency: "yearly",  priority: 0.3 },
    ...calculators.map(({ slug, priority, changeFreq }) => ({
      url: `${BASE}/${slug}`,
      lastModified: now,
      changeFrequency: changeFreq,
      priority,
    })),
    { url: `${BASE}/projects`, lastModified: now, changeFrequency: "monthly" as const, priority: 0.8 },
    ...projectBundles.map(({ slug, priority, changeFreq }) => ({
      url: `${BASE}/projects/${slug}`,
      lastModified: now,
      changeFrequency: changeFreq,
      priority,
    })),
  ];
}
